[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--force"
  VITE_API_URL = "https://your-backend-domain.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
